function sffis
%SFFIS	Fuzzy Inference S-function.
%	This is a SIMULINK S-function for fuzzy inference system; it is
%	called by the SIMULINK block of fuzzy controller in FUZBLOCK.
%	This function is not to be used directly. Use EVALFIS or FUZBLOCK
%	instead.
%
%	See also EVALFIS and FUZBLOCK.

%	Roger Jang, 1-17-95.
%       Copyright (c) 1994-95  by The MathWorks, Inc.
%       $Revision: 1.3 $  $Date: 1995/02/17 13:08:10 $
